"use client";

import { useEffect, useState, type FormEvent } from "react";
import type { LucideIcon } from "lucide-react";
import { ArrowDown, ArrowRight, ArrowUp, BarChart3, Check, Code2, FileText, Globe2, Link2, List, Mail, Menu, Palette, Plus, Send, Settings2, Share2, Sparkles, Trash2, Users, X, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";

type DemoTab = "forms" | "create" | "responses" | "brand";
const templates = [
  { name: "Cadastro de clientes", description: "Dados essenciais para conhecer seu cliente", fields: ["Nome ou razão social", "CPF ou CNPJ", "E-mail", "Telefone", "Cidade", "Atividade principal"] },
  { name: "Pedido de venda", description: "Itens, quantidades e condições comerciais", fields: ["Cliente", "Produto", "Quantidade", "Preço", "Condição de pagamento", "Data de entrega"] },
];
const cases = ["Cadastro de clientes", "Pedido de venda", "Solicitação de crédito", "Pesquisa de satisfação", "Registro de visitas", "Inscrição em eventos", "Solicitações internas"];
const nextSteps = ["Campos condicionais", "Upload de documentos", "Assinatura digital", "Fluxos de aprovação", "Notificações automáticas", "Dashboards e indicadores", "IA para criação de formulários", "Controle de permissões", "Formulários com múltiplas etapas"];
const scrollTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });

export function H2ONexoPage() {
  const [mobile, setMobile] = useState(false);
  const [tab, setTab] = useState<DemoTab>("forms");
  const [template, setTemplate] = useState(0);
  const [name, setName] = useState("Cadastro de clientes");
  const [fields, setFields] = useState(templates[0].fields);
  const [published, setPublished] = useState(true);
  const [responseStatus, setResponseStatus] = useState("Recebido");
  const [color, setColor] = useState("#43B9F1");
  const [sent, setSent] = useState(false);
  const [toast, setToast] = useState("");

  useEffect(() => {
    try {
      const saved = JSON.parse(localStorage.getItem("h2o-nexo-demo") || "null") as Partial<{ name: string; fields: string[]; published: boolean; color: string }> | null;
      if (saved?.name) setName(saved.name);
      if (saved?.fields?.length) setFields(saved.fields);
      if (typeof saved?.published === "boolean") setPublished(saved.published);
      if (saved?.color) setColor(saved.color);
    } catch { /* Mantém dados simulados. */ }
  }, []);
  useEffect(() => { localStorage.setItem("h2o-nexo-demo", JSON.stringify({ name, fields, published, color })); }, [name, fields, published, color]);
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2400); };
  const chooseTemplate = (index: number) => { setTemplate(index); setName(templates[index].name); setFields([...templates[index].fields]); setTab("create"); notify("Modelo carregado no construtor."); };
  const addField = () => setFields((current) => [...current, `Novo campo ${current.length + 1}`]);
  const moveField = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= fields.length) return; const next = [...fields]; [next[index], next[target]] = [next[target], next[index]]; setFields(next); };

  return <main className="min-h-screen overflow-x-hidden bg-[#101011] text-white selection:bg-blue-500/30">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#101011]/90 backdrop-blur-xl"><nav className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 lg:px-8"><a href="#top" className="group flex items-center gap-3" onClick={() => scrollTo("top")}><span className="grid h-9 w-9 place-items-center rounded-lg border border-[#43B9F1]/40 bg-[#43B9F1]/10 font-mono text-sm font-bold text-[#43B9F1] shadow-[0_0_24px_rgba(67,185,241,.13)] transition group-hover:scale-105">H₂O</span><span className="text-xl font-bold tracking-[-.06em]">Nexo<span className="ml-1 text-xs font-medium tracking-normal text-white/40">by H2O</span></span></a><div className="hidden items-center gap-1 md:flex">{[["Problema", "problema"], ["Solução", "solucao"], ["Como funciona", "como-funciona"], ["Demonstração", "demo"], ["Benefícios", "beneficios"], ["Diferenciais", "diferenciais"]].map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => scrollTo(id)} className="rounded-lg px-3 py-2 text-xs text-white/60 transition hover:bg-white/5 hover:text-[#43B9F1]">{label}</a>)}</div><div className="hidden items-center gap-3 md:flex"><span className="text-xs text-white/35">Demo local · Dados simulados</span><Button onClick={() => scrollTo("demo")} className="rounded-full bg-[#43B9F1] px-5 text-xs font-bold text-[#071016] shadow-[0_0_25px_rgba(67,185,241,.2)] hover:bg-[#67caf7]">Experimentar agora <ArrowRight className="ml-1 h-3.5 w-3.5"/></Button></div><button className="rounded-lg p-2 md:hidden" aria-label="Abrir menu" onClick={() => setMobile(!mobile)}>{mobile ? <X/> : <Menu/>}</button></nav>{mobile && <div className="border-t border-white/10 bg-[#151619] px-6 pb-5 md:hidden">{[["Problema", "problema"], ["Solução", "solucao"], ["Como funciona", "como-funciona"], ["Demonstração", "demo"], ["Benefícios", "beneficios"], ["Diferenciais", "diferenciais"]].map(([label, id]) => <a key={id} href={`#${id}`} className="block border-b border-white/10 py-3 text-sm text-white/70" onClick={() => { scrollTo(id); setMobile(false); }}>{label}</a>)}</div>}</header>

    <section id="top" className="relative isolate flex min-h-[780px] items-center overflow-hidden border-b border-white/10 pt-20"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_68%_42%,rgba(37,99,235,.22),transparent_27%),radial-gradient(circle_at_27%_50%,rgba(34,211,238,.1),transparent_25%)]"/><div className="pointer-events-none absolute inset-0 opacity-30 [background-image:radial-gradient(rgba(255,255,255,.42)_1px,transparent_1px)] [background-size:32px_32px] [mask-image:linear-gradient(to_bottom,black_0%,transparent_86%)]"/><div className="relative mx-auto grid w-full max-w-7xl items-center gap-14 px-6 py-20 lg:grid-cols-[.84fr_1.16fr] lg:px-8 lg:py-24"><div className="relative z-10 max-w-xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#43B9F1]/30 bg-[#43B9F1]/10 px-3 py-1.5 font-mono text-[10px] uppercase tracking-widest text-[#9edfff] animate-[fadeUp_.7s_ease-out_both]"><span className="h-1.5 w-1.5 rounded-full bg-[#2DDCFF] shadow-[0_0_12px_#2DDCFF]"/> Plataforma white label de formulários</div><h1 className="text-balance text-5xl font-semibold leading-[.95] tracking-[-.085em] sm:text-6xl lg:text-7xl animate-[fadeUp_.8s_.08s_ease-out_both]">Transforme formulários em <span className="text-[#43B9F1] [text-shadow:0_0_32px_rgba(67,185,241,.26)]">processos de negócio.</span></h1><p className="mt-7 max-w-lg text-base leading-relaxed text-white/60 sm:text-lg animate-[fadeUp_.8s_.16s_ease-out_both]">Crie formulários personalizados, compartilhe por link e centralize as respostas em uma experiência adaptada à identidade da sua empresa.</p><div className="mt-8 flex flex-wrap gap-3 animate-[fadeUp_.8s_.24s_ease-out_both]"><Button onClick={() => scrollTo("demo")} className="rounded-full bg-[#43B9F1] px-5 font-bold text-[#081218] hover:bg-[#6bd2fa]">Criar formulário <ArrowRight className="ml-2 h-4 w-4"/></Button><Button variant="outline" onClick={() => scrollTo("como-funciona")} className="rounded-full border-white/20 bg-white text-[#1556c9] hover:bg-blue-50">Ver como funciona</Button></div><div className="mt-7 flex items-center gap-3 text-[10px] text-white/40"><span className="text-[#76d6b0]">✓</span> Seguro por padrão <span className="h-1 w-1 rounded-full bg-white/30"/><span className="text-[#43B9F1]">✓</span> Sem desenvolvimento</div></div><HeroCanvas/></div></section>

    <section className="border-b border-white/10 px-6 py-12 lg:px-8"><div className="mx-auto grid max-w-6xl grid-cols-2 gap-8 sm:grid-cols-4">{[["12", "Formulários ativos"], ["16+", "Processos possíveis"], ["100%", "White label"], ["24/7", "Respostas centralizadas"]].map(([value, label]) => <div key={label}><strong className="block text-4xl font-bold tracking-[-.08em] text-[#43B9F1] sm:text-5xl">{value}</strong><span className="mt-2 block text-xs text-white/60 sm:text-sm">{label}</span></div>)}</div></section>

    <section id="problema" className="mx-auto max-w-7xl px-6 py-28 lg:px-8"><SectionHeader eyebrow="O desafio" title="Processos diferentes ainda dependem de ferramentas manuais." body="Planilhas, mensagens e documentos dispersos tornam a coleta de informações lenta, despadronizada e difícil de acompanhar."/><div className="grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 md:grid-cols-2 lg:grid-cols-3">{[["Dados incompletos ou desorganizados", "As informações chegam sem padrão e exigem conferência manual.", FileText], ["Retrabalho e erros de preenchimento", "Mais tempo corrigindo dados do que avançando o processo.", Zap], ["Demora para iniciar processos", "A resposta fica parada até alguém conseguir organizá-la.", BarChart3], ["Informações em diferentes canais", "E-mails, planilhas e mensagens espalham o contexto.", Share2], ["Falta de rastreabilidade", "É difícil saber quem respondeu e em qual etapa está.", Link2], ["Dependência da equipe técnica", "Cada nova necessidade vira uma fila de desenvolvimento.", Code2]].map(([title, body, Icon]) => <FeatureTile key={title as string} title={title as string} body={body as string} Icon={Icon as LucideIcon}/>)}</div><div className="mt-5 flex items-center gap-5 rounded-xl border border-[#43B9F1]/25 bg-[#43B9F1]/[.07] p-6 text-sm font-medium text-white/80"><span className="text-3xl text-[#43B9F1]">“</span><span className="flex-1">Quando cada necessidade exige um novo desenvolvimento, processos simples se tornam lentos e caros.</span><ArrowRight className="h-5 w-5 text-[#43B9F1]"/></div></section>

    <section id="solucao" className="border-y border-white/10 bg-[#151619] px-6 py-28 lg:px-8"><div className="mx-auto max-w-7xl"><SectionHeader eyebrow="A solução" title="Para empresas que precisam coletar informações e agir sobre elas." body="Uma base configurável para criar experiências de coleta que acompanham o ritmo de cada operação."/><div className="grid gap-4 lg:grid-cols-3">{[["Quem administra", "Cria, personaliza, publica e acompanha os formulários.", Settings2], ["Quem decide", "Consulta respostas e utiliza os dados nos processos da empresa.", BarChart3], ["Quem responde", "Preenche por meio de um link simples, sem acessar o painel.", Users]].map(([title, body, Icon]) => <div key={title as string} className="rounded-xl border border-white/10 bg-white/[.035] p-6 transition hover:-translate-y-1 hover:border-[#43B9F1]/50"><div className="mb-8 grid h-10 w-10 place-items-center rounded-lg bg-[#43B9F1]/10 text-[#43B9F1]"><Icon size={19}/></div><h3 className="font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-relaxed text-white/50">{body as string}</p></div>)}</div><div className="mt-12 flex flex-wrap items-center gap-2"><span className="mr-3 font-mono text-[10px] uppercase tracking-wider text-white/40">Feito para qualquer processo</span>{cases.map((item) => <span key={item} className="rounded-full border border-white/15 px-3 py-1.5 text-xs text-white/65">{item}</span>)}</div></div></section>

    <section id="como-funciona" className="mx-auto max-w-7xl px-6 py-28 lg:px-8"><SectionHeader eyebrow="O fluxo" title="Um formulário. Diversas possibilidades." body="H2O Nexo permite configurar a coleta de dados de acordo com cada necessidade, sem criar uma nova aplicação para cada processo."/><div className="grid gap-3 md:grid-cols-3 lg:grid-cols-6">{[["01", "Criar", "Comece com um modelo.", Plus], ["02", "Personalizar", "Adapte campos e marca.", Palette], ["03", "Publicar", "Deixe tudo pronto.", Globe2], ["04", "Compartilhar", "Envie um link simples.", Share2], ["05", "Responder", "Receba dados completos.", Users], ["06", "Acompanhar", "Transforme resposta em ação.", BarChart3]].map(([number, title, body, Icon], index) => <div key={title as string} className="group relative border-t border-[#43B9F1]/45 bg-gradient-to-b from-[#43B9F1]/10 to-transparent p-4"><span className="font-mono text-[10px] text-white/30">{number as string}</span><div className="my-5 grid h-9 w-9 place-items-center rounded-full border border-[#43B9F1]/50 bg-[#151619] text-[#43B9F1] transition group-hover:scale-110 group-hover:bg-[#43B9F1] group-hover:text-[#071016]"><Icon size={16}/></div><h3 className="text-sm font-semibold">{title as string}</h3><p className="mt-1 text-[10px] leading-relaxed text-white/45">{body as string}</p>{index < 5 && <ArrowRight className="absolute -right-4 top-9 z-10 hidden h-4 w-4 text-[#43B9F1] lg:block"/>}</div>)}</div></section>

    <section id="demo" className="border-y border-white/10 bg-[#0b0c0e] px-4 py-24 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mb-9 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="mb-4 flex items-center gap-2 font-mono text-[10px] uppercase tracking-widest text-[#43B9F1]"><span className="h-1.5 w-1.5 rounded-full bg-[#76d6b0] shadow-[0_0_10px_#76d6b0]"/> Experiência interativa</div><h2 className="text-4xl font-semibold tracking-[-.07em] sm:text-5xl">Experimente o H2O Nexo</h2><p className="mt-3 text-sm text-white/50">Crie, edite, publique e acompanhe. Tudo em um único lugar.</p></div><span className="font-mono text-[10px] text-white/35">DEMO LOCAL · DADOS SIMULADOS</span></div><div className="overflow-hidden rounded-2xl border border-white/15 bg-[#17181a] shadow-2xl"><div className="flex gap-1 overflow-x-auto border-b border-white/10 bg-[#121315] p-3">{([["forms", "Meus formulários", List], ["create", "Criar formulário", Plus], ["responses", "Respostas", Mail], ["brand", "Personalização", Palette]] as [DemoTab, string, LucideIcon][]).map(([key, label, Icon]) => <button key={key} onClick={() => setTab(key)} className={`flex shrink-0 items-center gap-2 rounded-lg px-4 py-2 text-xs transition ${tab === key ? "bg-[#43B9F1]/15 text-[#8edfff]" : "text-white/45 hover:bg-white/5 hover:text-white"}`}><Icon size={14}/>{label}{key === "responses" && <span className="rounded bg-[#43B9F1]/20 px-1.5 text-[10px] text-[#8edfff]">12</span>}</button>)}</div><div className="grid min-h-[550px] lg:grid-cols-[1.1fr_.9fr]">{tab === "forms" && <FormsPanel onNew={() => setTab("create")} onTemplate={chooseTemplate} published={published}/>} {tab === "create" && <BuilderPanel name={name} setName={setName} fields={fields} setFields={setFields} addField={addField} moveField={moveField} onSave={() => notify("Rascunho salvo com sucesso.")} onPublish={() => { setPublished(true); notify("Formulário publicado. Link pronto para compartilhar."); }}/>} {tab === "responses" && <ResponsesPanel status={responseStatus} setStatus={setResponseStatus}/>} {tab === "brand" && <BrandPanel color={color} setColor={(value) => { setColor(value); notify("Identidade atualizada na pré-visualização."); }}/>}<LivePreview name={name} fields={fields} color={color} sent={sent} onSubmit={(event) => { event.preventDefault(); setSent(true); setResponseStatus("Recebido"); notify("Resposta recebida e adicionada ao acompanhamento."); }}/></div></div></div></section>

    <section id="beneficios" className="mx-auto max-w-7xl px-6 py-28 lg:px-8"><SectionHeader eyebrow="O que muda" title="Autonomia para criar. Agilidade para executar." body="As equipes ganham autonomia para digitalizar processos sem depender da criação de uma nova ferramenta para cada necessidade."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["Criação rápida sem novo desenvolvimento", "Dados completos e padronizados", "Menos erros e retrabalho", "Respostas centralizadas", "Maior rastreabilidade", "Adaptação a diferentes processos", "Reutilização em diferentes empresas", "Redução do tempo entre necessidade e execução"].map((item, index) => <div key={item} className="flex items-start gap-3 border-t border-white/15 py-5 text-sm text-white/70"><span className="font-mono text-[10px] text-[#43B9F1]">0{index + 1}</span><Check className="h-4 w-4 shrink-0 text-[#76d6b0]"/>{item}</div>)}</div></section>

    <section id="diferenciais" className="border-y border-white/10 bg-[#151619] px-6 py-28 lg:px-8"><div className="mx-auto max-w-7xl"><SectionHeader eyebrow="Por que Nexo" title="Muito além de um formulário." body="Ferramentas comuns coletam respostas. H2O Nexo transforma respostas em ações."/><div className="grid gap-12 lg:grid-cols-2"><div className="grid gap-2">{["Personalização white label", "Formulários adaptáveis", "Modelos prontos", "Centralização das respostas", "Rastreabilidade dos processos", "Preparado para integrações"].map((item) => <div key={item} className="flex items-center gap-3 rounded-lg border border-white/10 bg-white/[.025] p-4 text-sm text-white/75 transition hover:border-[#43B9F1]/50 hover:bg-[#43B9F1]/[.06]"><span className="grid h-6 w-6 place-items-center rounded-full bg-[#43B9F1]/15 text-[#43B9F1]"><Check size={13}/></span>{item}<ArrowRight className="ml-auto h-4 w-4 text-white/25"/></div>)}</div><div className="relative overflow-hidden rounded-2xl border border-[#43B9F1]/25 bg-[#0c0e11] p-8"><div className="absolute inset-0 opacity-20 [background-image:radial-gradient(#43B9F1_1px,transparent_1px)] [background-size:20px_20px]"/><div className="relative flex min-h-52 flex-col items-center justify-center gap-5 sm:flex-row"><div className="text-center"><span className="block text-xs text-white/40">Coletam e armazenam</span><strong className="mt-2 block text-xl text-white">respostas</strong></div><ArrowRight className="text-[#43B9F1]"/><div className="text-center"><span className="block text-xs text-white/40">Conecta dados a</span><strong className="mt-2 block text-xl text-[#43B9F1]">processos de negócio</strong></div></div></div></div></div></section>

    <section className="border-b border-white/10 bg-[#0f151c] px-6 py-28 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[.85fr_1.15fr]"><div><div className="mb-5 flex items-center gap-2 font-mono text-[10px] uppercase tracking-widest text-[#43B9F1]"><span className="h-1.5 w-1.5 rounded-full bg-[#2DDCFF]"/> Ecossistema H2O</div><h2 className="text-4xl font-semibold tracking-[-.07em] sm:text-5xl">Preparado para evoluir dentro do ecossistema H2O.</h2><p className="mt-6 max-w-md text-sm leading-relaxed text-white/50">No MVP, as integrações são representadas por dados simulados e uma camada de serviços preparada para conexão futura.</p><span className="mt-7 inline-flex rounded-full border border-[#43B9F1]/25 bg-[#43B9F1]/10 px-3 py-1.5 font-mono text-[10px] text-[#8edfff]">PRÓXIMAS INTEGRAÇÕES</span></div><div className="relative grid min-h-80 place-items-center rounded-2xl border border-[#43B9F1]/20 bg-[#101114] p-7 [background-image:radial-gradient(rgba(67,185,241,.35)_1px,transparent_1px)] [background-size:18px_18px]"><div className="absolute h-px w-2/3 bg-gradient-to-r from-transparent via-[#43B9F1] to-transparent"/><div className="relative z-10 grid h-24 w-24 place-items-center rounded-2xl border border-[#43B9F1] bg-[#1a2b3a] shadow-[0_0_50px_rgba(67,185,241,.28)]"><span className="font-mono text-xs text-[#43B9F1]">H₂O</span><strong className="text-xs">Nexo</strong></div>{["Aplicativos H2O", "Backoffice", "CRM", "ERP", "Análise de crédito", "WhatsApp e e-mail", "Assinatura digital", "Fluxos de aprovação"].map((item, index) => <span key={item} className={`absolute rounded-md border border-white/20 bg-[#20262d] px-2.5 py-2 text-[9px] text-white/65 shadow-xl ${["left-4 top-8", "left-5 bottom-8", "left-[38%] top-3", "right-4 top-8", "right-2 bottom-8", "left-[35%] bottom-3", "right-[22%] bottom-2", "right-[27%] top-1/2"][index]}`}><span className="mr-1.5 inline-block h-1.5 w-1.5 rounded-full bg-[#43B9F1]"/>{item}</span>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-6 py-28 lg:px-8"><SectionHeader eyebrow="Próximos passos" title="Uma plataforma preparada para crescer." body="O núcleo é configurável desde já. Novas camadas entram quando o processo pedir."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{nextSteps.map((item) => <div key={item} className="flex items-center gap-3 rounded-lg border border-white/10 bg-white/[.02] p-4 text-sm text-white/60 transition hover:-translate-y-1 hover:border-[#43B9F1]/40"><Sparkles className="h-4 w-4 text-[#43B9F1]"/>{item}<span className="ml-auto rounded bg-white/5 px-2 py-1 font-mono text-[8px] text-white/35">FUTURO</span></div>)}</div></section>

    <section className="relative overflow-hidden border-t border-white/10 bg-[#0c1620] px-6 py-32 text-center lg:px-8"><div className="absolute left-1/2 top-1/2 h-80 w-80 -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#2563eb]/20 blur-[100px]"/><div className="relative mx-auto max-w-3xl"><div className="mb-5 flex items-center justify-center gap-2 font-mono text-[10px] uppercase tracking-widest text-[#43B9F1]"><span className="h-1.5 w-1.5 rounded-full bg-[#2DDCFF]"/> Pronto para começar?</div><h2 className="text-4xl font-semibold tracking-[-.08em] sm:text-6xl">Cada formulário pode ser o início de um novo processo.</h2><p className="mx-auto mt-6 max-w-lg text-sm leading-relaxed text-white/55">Crie experiências personalizadas, centralize informações e transforme respostas em ações para o seu negócio.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><Button onClick={() => scrollTo("demo")} className="rounded-full bg-[#43B9F1] px-5 font-bold text-[#071016] hover:bg-[#6bd2fa]">Criar meu formulário <ArrowRight className="ml-2 h-4 w-4"/></Button><Button variant="outline" onClick={() => scrollTo("demo")} className="rounded-full border-white/20 bg-white text-[#1556c9] hover:bg-blue-50">Explorar demonstração</Button></div></div></section>
    <footer className="border-t border-white/10 px-6 py-8 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 text-center sm:flex-row sm:text-left"><a href="#top" className="flex items-center gap-2 text-lg font-bold tracking-[-.06em]"><span className="font-mono text-[#43B9F1]">H₂O</span> Nexo</a><span className="text-xs text-white/40">Crie, compartilhe e transforme respostas em ações.</span><span className="text-xs text-white/30">© 2026 H2O Nexo</span></div></footer>
    {toast && <div className="fixed bottom-6 right-6 z-[60] flex items-center gap-2 rounded-lg border border-[#76d6b0]/40 bg-[#17352d] px-4 py-3 text-xs text-[#dff9ed] shadow-xl"><Check className="h-4 w-4 text-[#76d6b0]"/>{toast}</div>}
  </main>;
}

function SectionHeader({ eyebrow, title, body }: { eyebrow: string; title: string; body: string }) { return <div className="mb-12 grid gap-7 lg:grid-cols-[1.05fr_.95fr] lg:items-end"><div><div className="mb-4 flex items-center gap-2 font-mono text-[10px] uppercase tracking-widest text-[#43B9F1]"><span className="h-1.5 w-1.5 rounded-full bg-[#2DDCFF]"/>{eyebrow}</div><h2 className="text-4xl font-semibold leading-[1.03] tracking-[-.075em] text-balance sm:text-5xl">{title}</h2></div><p className="max-w-md text-sm leading-relaxed text-white/50 lg:mb-1">{body}</p></div>; }
function FeatureTile({ title, body, Icon }: { title: string; body: string; Icon: LucideIcon }) { return <article className="group bg-[#151619] p-6 transition hover:bg-[#1b1d20]"><div className="mb-8 grid h-10 w-10 place-items-center rounded-lg border border-[#43B9F1]/25 bg-[#43B9F1]/10 text-[#43B9F1] transition group-hover:scale-110 group-hover:bg-[#43B9F1] group-hover:text-[#071016]"><Icon size={18}/></div><h3 className="text-sm font-semibold">{title}</h3><p className="mt-2 max-w-xs text-xs leading-relaxed text-white/45">{body}</p></article>; }
function HeroCanvas() { return <div className="relative h-[430px] animate-[fadeIn_.9s_.15s_ease-out_both] lg:h-[500px]"><div className="absolute inset-0 rounded-[45%] bg-[#2563eb]/10 blur-3xl"/><div className="absolute inset-0 [background-image:radial-gradient(rgba(255,255,255,.38)_1px,transparent_1px)] [background-size:22px_22px] opacity-45 [mask-image:radial-gradient(ellipse_at_center,black_18%,transparent_76%)]"/><div className="absolute left-[25%] top-[28%] h-px w-[24%] rotate-[14deg] bg-gradient-to-r from-[#c8cdd6] via-[#43B9F1] to-transparent [background-size:14px_1px]"/><div className="absolute left-[24%] top-[55%] h-px w-[31%] -rotate-[12deg] bg-gradient-to-r from-[#c8cdd6] via-[#43B9F1] to-transparent [background-size:14px_1px]"/><div className="absolute left-[50%] top-[48%] h-px w-[26%] -rotate-[35deg] bg-gradient-to-r from-[#c8cdd6] via-[#43B9F1] to-transparent [background-size:14px_1px]"/><CanvasNode className="left-[7%] top-[15%]" label="formulário" title="Cadastro de clientes" meta="6 campos ativos"/><CanvasNode className="left-0 top-[53%]" label="personalizar" title="Sua marca" meta="white label"/><div className="absolute right-[1%] top-[21%] h-[230px] w-[47%] rounded-2xl border border-white/20 bg-[#111214]/95 p-4 shadow-[0_25px_70px_rgba(0,0,0,.45)] backdrop-blur-xl"><div className="flex items-center justify-between border-b border-white/10 pb-3"><span className="text-xs text-white">respostas</span><span className="rounded-full bg-[#76d6b0]/10 px-2 py-1 text-[9px] text-[#76d6b0]">Publicado</span></div><div className="relative mt-5 h-28 overflow-hidden rounded-lg border border-[#43B9F1]/20 bg-[#0a1117] [background-image:radial-gradient(#43B9F1_1px,transparent_1px)] [background-size:13px_13px]"><div className="absolute left-1/2 top-1/2 h-3 w-3 -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#43B9F1] shadow-[0_0_18px_#43B9F1]"/><div className="absolute left-[28%] top-[38%] h-2 w-2 rounded-full bg-[#2DDCFF]"/><div className="absolute left-[63%] top-[30%] h-2 w-2 rounded-full bg-[#43B9F1]"/><div className="absolute left-[72%] top-[68%] h-3 w-3 rounded bg-[#2563eb] shadow-[0_0_14px_#2563eb]"/><div className="absolute left-[40%] top-[70%] h-2 w-2 rounded-full bg-[#2DDCFF]"/></div><div className="mt-4 flex items-center justify-between text-[10px] text-white/40"><span><b className="text-lg text-white">12</b> respostas</span><span className="flex items-center gap-1 text-[#43B9F1]"><Share2 size={12}/> Compartilhar</span></div></div><div className="absolute bottom-4 left-1/2 -translate-x-1/2 rounded-full border border-[#43B9F1]/30 bg-[#43B9F1]/10 px-4 py-2 text-[10px] text-[#aee9ff]">Cadastro de clientes, pedidos e muito mais <ArrowRight className="ml-1 inline h-3 w-3"/></div></div>; }
function CanvasNode({ className, label, title, meta }: { className: string; label: string; title: string; meta: string }) { return <div className={`absolute z-10 w-40 rounded-xl border border-white/20 bg-[#111214]/95 p-4 shadow-xl backdrop-blur-xl transition hover:-translate-y-1 hover:border-[#2DDCFF] ${className}`}><span className="mb-3 block text-[10px] text-white/75">{label}</span><strong className="block text-xs text-white/80">{title}</strong><span className="mt-5 block text-[9px] text-white/40"><span className="mr-1.5 inline-block h-1.5 w-1.5 rounded-full bg-[#43B9F1]"/>{meta}</span><span className="absolute -right-1.5 top-1/2 h-3 w-3 rounded-full border-2 border-[#aeb9c8] bg-[#aeb9c8]"/></div>; }
function FormsPanel({ onNew, onTemplate, published }: { onNew: () => void; onTemplate: (index: number) => void; published: boolean }) { return <div className="p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-widest text-white/35">Workspace / formulários</p><h3 className="mt-2 text-2xl font-semibold tracking-[-.06em]">Meus formulários</h3><p className="mt-2 text-xs text-white/45">Crie experiências de coleta para cada etapa do seu negócio.</p></div><Button onClick={onNew} className="rounded-lg bg-[#43B9F1] px-3 text-xs font-bold text-[#071016]"><Plus className="mr-1 h-4 w-4"/> Novo</Button></div><div className="mt-8 grid gap-3">{templates.map((item, index) => <div key={item.name} className="rounded-xl border border-white/10 bg-white/[.025] p-4 transition hover:border-[#43B9F1]/40"><div className="flex items-start gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-[#43B9F1]/10 text-[#43B9F1]"><FileText size={16}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><strong className="text-sm">{item.name}</strong><span className={`rounded px-2 py-0.5 text-[9px] ${index === 0 && published ? "bg-[#76d6b0]/10 text-[#76d6b0]" : "bg-amber-300/10 text-amber-200"}`}>{index === 0 && published ? "Publicado" : "Rascunho"}</span></div><p className="mt-1 text-[10px] text-white/35">h2onexo.app/f/{index === 0 ? "cadastro-clientes" : "pedido-de-venda"}</p></div><span className="font-mono text-sm text-white/70">{index === 0 ? 12 : 4}</span></div><div className="mt-4 flex gap-2 border-t border-white/10 pt-3"><button onClick={() => onTemplate(index)} className="text-[10px] text-[#43B9F1]">Editar</button><button className="text-[10px] text-white/45">Visualizar</button><button className="text-[10px] text-white/45">{index === 0 && published ? "Compartilhar" : "Publicar"}</button></div></div>)}</div></div>; }
function BuilderPanel({ name, setName, fields, setFields, addField, moveField, onSave, onPublish }: { name: string; setName: (value: string) => void; fields: string[]; setFields: (value: string[]) => void; addField: () => void; moveField: (index: number, direction: -1 | 1) => void; onSave: () => void; onPublish: () => void }) { return <div className="p-6 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-widest text-white/35">Workspace / criar formulário</p><h3 className="mt-2 text-2xl font-semibold tracking-[-.06em]">Construtor</h3></div><div className="flex gap-2"><Button onClick={onSave} variant="outline" className="rounded-lg border-white/15 bg-transparent text-[10px] text-white/60">Salvar rascunho</Button><Button onClick={onPublish} className="rounded-lg bg-[#43B9F1] text-[10px] font-bold text-[#071016]"><Globe2 className="mr-1 h-3.5 w-3.5"/> Publicar</Button></div></div><label className="mt-7 block text-[10px] text-white/50">Nome do formulário<input value={name} onChange={(event) => setName(event.target.value)} className="mt-2 w-full rounded-lg border border-white/10 bg-[#101114] px-3 py-2.5 text-sm text-white outline-none focus:border-[#43B9F1]"/></label><div className="mt-6 flex items-center justify-between border-b border-white/10 pb-3"><span className="text-xs font-semibold">Campos <b className="ml-1 font-mono text-[#43B9F1]">{fields.length}</b></span><button onClick={addField} className="flex items-center gap-1 text-[10px] text-[#43B9F1]"><Plus size={13}/> Adicionar campo</button></div><div className="mt-3 grid max-h-80 gap-2 overflow-auto">{fields.map((field, index) => <div key={`${field}-${index}`} className="flex items-center gap-2 rounded-lg border border-white/10 bg-white/[.025] p-2"><span className="font-mono text-[9px] text-white/25">{String(index + 1).padStart(2, "0")}</span><input value={field} onChange={(event) => setFields(fields.map((value, itemIndex) => itemIndex === index ? event.target.value : value))} className="min-w-0 flex-1 bg-transparent px-1 text-xs text-white/75 outline-none"/><button onClick={() => moveField(index, -1)} disabled={index === 0} className="text-white/30 hover:text-[#43B9F1] disabled:opacity-20" aria-label="Subir campo"><ArrowUp size={13}/></button><button onClick={() => moveField(index, 1)} disabled={index === fields.length - 1} className="text-white/30 hover:text-[#43B9F1] disabled:opacity-20" aria-label="Baixar campo"><ArrowDown size={13}/></button><button onClick={() => setFields(fields.filter((_, itemIndex) => itemIndex !== index))} className="text-white/30 hover:text-red-300" aria-label="Excluir campo"><Trash2 size={13}/></button></div>)}</div></div>; }
function LivePreview({ name, fields, color, sent, onSubmit }: { name: string; fields: string[]; color: string; sent: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="border-l border-white/10 bg-[#f5f8f9] p-5 text-[#213038] sm:p-8"><div className="mx-auto max-w-md rounded-xl bg-white p-6 shadow-2xl"><div className="flex items-center gap-2 text-xs font-bold"><span className="grid h-7 w-7 place-items-center rounded bg-[#213038] text-[9px] text-white" style={{ background: color }}>H₂O</span> H2O Nexo</div><div className="mt-10"><span className="font-mono text-[9px] uppercase tracking-widest" style={{ color }}>Pré-visualização</span><h3 className="mt-2 text-2xl font-bold tracking-[-.07em]">{sent ? "Resposta recebida!" : name}</h3><p className="mt-2 text-xs leading-relaxed text-[#718087]">{sent ? "Obrigado. Seus dados foram enviados para acompanhamento." : "Preencha as informações para começar."}</p></div>{sent ? <div className="mt-8 rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-xs text-emerald-700"><Check className="mb-2 h-5 w-5"/> {name} está em acompanhamento.</div> : <form onSubmit={onSubmit} className="mt-7 space-y-3">{fields.slice(0, 5).map((field) => <label key={field} className="block text-[10px] font-semibold text-[#405158]">{field}<input required className="mt-1.5 w-full rounded-md border border-[#dbe3e5] px-3 py-2.5 text-xs font-normal outline-none focus:border-blue-400" placeholder={`Digite ${field.toLowerCase()}`}/></label>)}<button className="mt-4 flex w-full items-center justify-center gap-2 rounded-md py-3 text-xs font-bold text-white" style={{ background: color }}>Enviar resposta <Send size={13}/></button></form>}<span className="mt-5 block text-center text-[9px] text-[#a8b3b6]">Powered by H2O Nexo</span></div></div>; }
function ResponsesPanel({ status, setStatus }: { status: string; setStatus: (value: string) => void }) { const responses = [["Mariana Costa", "Cadastro de clientes", "27 ago 2026, 09:42", "Recebido"], ["João Oliveira", "Cadastro de clientes", "26 ago 2026, 16:10", "Em análise"], ["Bruna Martins", "Pedido de venda", "26 ago 2026, 11:06", "Concluído"]]; return <div className="p-6 sm:p-8 lg:col-span-2"><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-widest text-white/35">Workspace / acompanhamento</p><h3 className="mt-2 text-2xl font-semibold tracking-[-.06em]">Respostas</h3><p className="mt-2 text-xs text-white/45">Formulário <ArrowRight className="mx-1 inline h-3 w-3"/> Resposta <ArrowRight className="mx-1 inline h-3 w-3"/> Status <ArrowRight className="mx-1 inline h-3 w-3"/> Acompanhamento</p></div><span className="font-mono text-3xl text-[#43B9F1]">12</span></div><div className="mt-8 overflow-hidden rounded-xl border border-white/10">{responses.map(([person, form, date, initialStatus], index) => <div key={person} className="grid gap-3 border-b border-white/10 p-4 last:border-0 sm:grid-cols-[1.2fr_1fr_1fr_1fr]"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#43B9F1]/15 font-mono text-[9px] text-[#43B9F1]">{person.split(" ").map((word) => word[0]).join("")}</span><span className="text-xs"><strong className="block">{person}</strong><small className="text-[9px] text-white/35">cliente@empresa.com</small></span></div><span className="text-xs text-white/50">{form}</span><span className="text-xs text-white/40">{date}</span>{index === 0 ? <select value={status} onChange={(event) => setStatus(event.target.value)} className="w-fit rounded border border-white/10 bg-[#101114] px-2 py-1 text-[10px] text-[#43B9F1] outline-none"><option>Recebido</option><option>Em análise</option><option>Concluído</option><option>Rejeitado</option></select> : <span className="w-fit rounded bg-[#43B9F1]/10 px-2 py-1 text-[10px] text-[#43B9F1]">{initialStatus}</span>}</div>)}</div></div>; }
function BrandPanel({ color, setColor }: { color: string; setColor: (value: string) => void }) { return <div className="p-6 sm:p-8"><p className="font-mono text-[10px] uppercase tracking-widest text-white/35">Workspace / identidade</p><h3 className="mt-2 text-2xl font-semibold tracking-[-.06em]">Sua marca. Seus formulários.</h3><p className="mt-2 text-xs text-white/45">Personalize a experiência de acordo com a identidade de cada empresa.</p><div className="mt-8 grid gap-5 sm:grid-cols-2"><label className="text-[10px] text-white/50">Nome da empresa<input defaultValue="Acme Corporation" className="mt-2 w-full rounded-lg border border-white/10 bg-[#101114] px-3 py-2.5 text-xs text-white outline-none"/></label><label className="text-[10px] text-white/50">Logo ou iniciais<input defaultValue="AC" maxLength={3} className="mt-2 w-full rounded-lg border border-white/10 bg-[#101114] px-3 py-2.5 text-xs text-white outline-none"/></label></div><div className="mt-7 flex items-center gap-4"><label className="text-[10px] text-white/50">Cor principal<input type="color" value={color} onChange={(event) => setColor(event.target.value)} className="ml-3 h-8 w-12 rounded border-0 bg-transparent align-middle"/></label><span className="font-mono text-xs text-white/40">{color}</span></div></div>; }
